USE q78f0ljfkc3as6y6;

CREATE TABLE burgers(
    id INTEGER NOT NULL AUTO_INCREMENT, 
    burger_name VARCHAR(45) NULL,
    devoured BOOLEAN DEFAULT false,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

#DROP TABLE burgers;

SELECT * FROM burgers;